<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="fusion-row" style="">
        <section id="content" style="width: 100%;">
            <div id="post-3289" class="post-3289 page type-page status-publish hentry">
                <span class="entry-title rich-snippet-hidden">Blood Facts</span><span class="vcard rich-snippet-hidden"><span class="fn"><a href="https://www.rrvbc.org/author/bgarrett/" title="Posts by Bryan Garrett" rel="author">Bryan Garrett</a></span></span><span class="updated rich-snippet-hidden">2020-05-06T17:50:49-05:00</span>

                <div class="post-content">
                    <div class="fusion-fullwidth fullwidth-box fusion-builder-row-1 nonhundred-percent-fullwidth non-hundred-percent-height-scrolling" style="background-color: rgba(255,255,255,0);background-position: center center;background-repeat: no-repeat;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;margin-bottom: 75px;margin-top: 0px;border-width: 0px 0px 0px 0px;border-color:#eae9e9;border-style:solid;"><div class="fusion-builder-row fusion-row"><div class="fusion-layout-column fusion_builder_column fusion-builder-column-0 fusion_builder_column_1_1 1_1 fusion-one-full fusion-column-first fusion-column-last" style="margin-top:0px;margin-bottom:0px;"><div class="fusion-column-wrapper fusion-flex-column-wrapper-legacy" style="background-position: left top; background-repeat: no-repeat; background-size: cover; padding: 0px; min-height: 0px;"><div class="fusion-text fusion-text-1"><p style="text-align: center;"><span style="color: #b5121b; font-size: 2em;">Explore your blood type below</span></p>
                    </div><div class="fusion-flip-boxes flip-boxes row fusion-columns-4 flip-effect-classic"><div class="fusion-flip-box-wrapper fusion-column col-lg-3 col-md-3 col-sm-3"><div class="fusion-flip-box flip-right" tabindex="0"><div class="flip-box-inner-wrapper" style="min-height: 252px;"><div class="flip-box-front" style="background-color: rgb(246, 246, 246); border-color: rgba(0, 0, 0, 0); border-radius: 4px; border-style: solid; border-width: 1px; color: rgb(116, 116, 116); transition-duration: 0.4s; position: absolute;"><div class="flip-box-front-inner"><div class="flip-box-grafix flip-box-image"><img src="https://rrvblood.wpengine.com/wp-content/uploads/2017/06/0.png" width="147" height="147" alt=""></div><h2 class="flip-box-heading without-text fusion-responsive-typography-calculated" style="color: rgb(51, 51, 51); --fontSize:26; line-height: 1.5;" data-fontsize="26" data-lineheight="39px">O Positive</h2></div></div><div class="flip-box-back" style="background-color: rgb(181, 18, 27); border-color: rgba(0, 0, 0, 0); border-radius: 4px; border-style: solid; border-width: 1px; color: rgb(255, 255, 255); transition-duration: 0.4s; bottom: 0px;"><div class="flip-box-back-inner">
                        <p style="text-align: center;"><strong>39% of the U.S. population has O+ blood</strong></p>
                        <p style="text-align: center; font-size: 13px; line-height: 18px;">• Most common blood type<br>
                            • Most transfused blood type<br>
                            • Can be given to most patients<br>
                            • Whole blood and double red cell needed most</p>
                    </div></div></div></div></div><div class="fusion-flip-box-wrapper fusion-column col-lg-3 col-md-3 col-sm-3"><div class="fusion-flip-box flip-right" tabindex="0"><div class="flip-box-inner-wrapper" style="min-height: 252px;"><div class="flip-box-front" style="background-color: rgb(246, 246, 246); border-color: rgba(0, 0, 0, 0); border-radius: 4px; border-style: solid; border-width: 1px; color: rgb(116, 116, 116); transition-duration: 0.4s; position: absolute;"><div class="flip-box-front-inner"><div class="flip-box-grafix flip-box-image"><img src="https://rrvblood.wpengine.com/wp-content/uploads/2017/06/0-1-1.png" width="147" height="147" alt=""></div><h2 class="flip-box-heading without-text fusion-responsive-typography-calculated" style="color: rgb(51, 51, 51); --fontSize:26; line-height: 1.5;" data-fontsize="26" data-lineheight="39px">O Negative</h2></div></div><div class="flip-box-back" style="background-color: rgb(181, 18, 27); border-color: rgba(0, 0, 0, 0); border-radius: 4px; border-style: solid; border-width: 1px; color: rgb(255, 255, 255); transition-duration: 0.4s; bottom: 0px;"><div class="flip-box-back-inner">
                        <p style="text-align: center;"><strong>9% of the U.S. population has O- blood</strong></p>
                        <p style="text-align: center; font-size: 13px; line-height: 18px;">• Universal red blood cell donor<br>
                            • Can be given to all patients<br>
                            • Can only receive O- blood<br>
                            • Whole blood and double red cells needed most</p>
                    </div></div></div></div></div><div class="fusion-flip-box-wrapper fusion-column col-lg-3 col-md-3 col-sm-3"><div class="fusion-flip-box flip-right" tabindex="0"><div class="flip-box-inner-wrapper" style="min-height: 252px;"><div class="flip-box-front" style="background-color: rgb(246, 246, 246); border-color: rgba(0, 0, 0, 0); border-radius: 4px; border-style: solid; border-width: 1px; color: rgb(116, 116, 116); transition-duration: 0.4s; position: absolute;"><div class="flip-box-front-inner"><div class="flip-box-grafix flip-box-image"><img src="https://rrvblood.wpengine.com/wp-content/uploads/2017/06/A.png" width="147" height="147" alt=""></div><h2 class="flip-box-heading without-text fusion-responsive-typography-calculated" style="color: rgb(51, 51, 51); --fontSize:26; line-height: 1.5;" data-fontsize="26" data-lineheight="39px">A Positive</h2></div></div><div class="flip-box-back" style="background-color: rgb(181, 18, 27); border-color: rgba(0, 0, 0, 0); border-radius: 4px; border-style: solid; border-width: 1px; color: rgb(255, 255, 255); transition-duration: 0.4s; bottom: 0px;"><div class="flip-box-back-inner">
                        <p style="text-align: center;"><strong>30% of the U.S. population has A+ blood</strong></p>
                        <p style="text-align: center; font-size: 13px; line-height: 18px;">• Tremendous demand for A+ platelets<br>
                            • 2nd most common blood type<br>
                            • Consider platelet pheresis as the best way to help</p>
                    </div></div></div></div></div><div class="fusion-flip-box-wrapper fusion-column col-lg-3 col-md-3 col-sm-3"><div class="fusion-flip-box flip-right" tabindex="0"><div class="flip-box-inner-wrapper" style="min-height: 252px;"><div class="flip-box-front" style="background-color: rgb(246, 246, 246); border-color: rgba(0, 0, 0, 0); border-radius: 4px; border-style: solid; border-width: 1px; color: rgb(116, 116, 116); transition-duration: 0.4s; position: absolute;"><div class="flip-box-front-inner"><div class="flip-box-grafix flip-box-image"><img src="https://rrvblood.wpengine.com/wp-content/uploads/2017/06/A-.png" width="147" height="147" alt=""></div><h2 class="flip-box-heading without-text fusion-responsive-typography-calculated" style="color: rgb(51, 51, 51); --fontSize:26; line-height: 1.5;" data-fontsize="26" data-lineheight="39px">A Negative</h2></div></div><div class="flip-box-back" style="background-color: rgb(181, 18, 27); border-color: rgba(0, 0, 0, 0); border-radius: 4px; border-style: solid; border-width: 1px; color: rgb(255, 255, 255); transition-duration: 0.4s; bottom: 0px;"><div class="flip-box-back-inner">
                        <p style="text-align: center;"><strong>6% of the U.S. population has A- blood</strong></p>
                        <p style="text-align: center; font-size: 13px; line-height: 18px;">• Rare blood type<br>
                            • Donate whole blood or automated red cells<br>
                            • Plasma and platelet pheresis are also needed</p>
                    </div></div></div></div></div><div class="fusion-flip-box-wrapper fusion-column col-lg-3 col-md-3 col-sm-3"><div class="fusion-flip-box flip-right" tabindex="0"><div class="flip-box-inner-wrapper" style="min-height: 252px;"><div class="flip-box-front" style="background-color: rgb(246, 246, 246); border-color: rgba(0, 0, 0, 0); border-radius: 4px; border-style: solid; border-width: 1px; color: rgb(116, 116, 116); transition-duration: 0.4s; position: absolute;"><div class="flip-box-front-inner"><div class="flip-box-grafix flip-box-image"><img src="https://rrvblood.wpengine.com/wp-content/uploads/2017/06/B.png" width="147" height="147" alt=""></div><h2 class="flip-box-heading without-text fusion-responsive-typography-calculated" style="color: rgb(51, 51, 51); --fontSize:26; line-height: 1.5;" data-fontsize="26" data-lineheight="39px">B Positive</h2></div></div><div class="flip-box-back" style="background-color: rgb(181, 18, 27); border-color: rgba(0, 0, 0, 0); border-radius: 4px; border-style: solid; border-width: 1px; color: rgb(255, 255, 255); transition-duration: 0.4s; bottom: 0px;"><div class="flip-box-back-inner">
                        <p style="text-align: center;"><strong>9% of the U.S. population has B+ blood</strong></p>
                        <p style="text-align: center; font-size: 13px; line-height: 18px;">• Can donate only to B+ and AB+ patients<br>
                            • Can receive most blood types<br>
                            • Donate platelets, plasma and red cells</p>
                    </div></div></div></div></div><div class="fusion-flip-box-wrapper fusion-column col-lg-3 col-md-3 col-sm-3"><div class="fusion-flip-box flip-right" tabindex="0"><div class="flip-box-inner-wrapper" style="min-height: 252px;"><div class="flip-box-front" style="background-color: rgb(246, 246, 246); border-color: rgba(0, 0, 0, 0); border-radius: 4px; border-style: solid; border-width: 1px; color: rgb(116, 116, 116); transition-duration: 0.4s; position: absolute;"><div class="flip-box-front-inner"><div class="flip-box-grafix flip-box-image"><img src="https://rrvblood.wpengine.com/wp-content/uploads/2017/06/B-.png" width="147" height="147" alt=""></div><h2 class="flip-box-heading without-text fusion-responsive-typography-calculated" style="color: rgb(51, 51, 51); --fontSize:26; line-height: 1.5;" data-fontsize="26" data-lineheight="39px">B Negative</h2></div></div><div class="flip-box-back" style="background-color: rgb(181, 18, 27); border-color: rgba(0, 0, 0, 0); border-radius: 4px; border-style: solid; border-width: 1px; color: rgb(255, 255, 255); transition-duration: 0.4s; bottom: 0px;"><div class="flip-box-back-inner">
                        <p style="text-align: center;"><strong>2% of the U.S. population has B- blood</strong></p>
                        <p style="text-align: center; font-size: 13px; line-height: 18px;">• Very rare blood type<br>
                            • Donate whole blood or automated red cells<br>
                            • Plasma and platelet pheresis are also needed</p>
                    </div></div></div></div></div><div class="fusion-flip-box-wrapper fusion-column col-lg-3 col-md-3 col-sm-3"><div class="fusion-flip-box flip-right" tabindex="0"><div class="flip-box-inner-wrapper" style="min-height: 252px;"><div class="flip-box-front" style="background-color: rgb(246, 246, 246); border-color: rgba(0, 0, 0, 0); border-radius: 4px; border-style: solid; border-width: 1px; color: rgb(116, 116, 116); transition-duration: 0.4s; position: absolute;"><div class="flip-box-front-inner"><div class="flip-box-grafix flip-box-image"><img src="https://rrvblood.wpengine.com/wp-content/uploads/2017/06/AB.png" width="147" height="147" alt=""></div><h2 class="flip-box-heading without-text fusion-responsive-typography-calculated" style="color: rgb(51, 51, 51); --fontSize:26; line-height: 1.5;" data-fontsize="26" data-lineheight="39px">AB Positive</h2></div></div><div class="flip-box-back" style="background-color: rgb(181, 18, 27); border-color: rgba(0, 0, 0, 0); border-radius: 4px; border-style: solid; border-width: 1px; color: rgb(255, 255, 255); transition-duration: 0.4s; bottom: 0px;"><div class="flip-box-back-inner">
                        <p style="text-align: center;"><strong>4% of the U.S. population has AB+ blood</strong></p>
                        <p style="text-align: center; font-size: 13px; line-height: 18px;">• Very rare blood type<br>
                            • Can donate only to AB+ patients<br>
                            • Universal Plasma donor<br>
                            • Plasma and platelet pheresis is the best way to help</p>
                    </div></div></div></div></div><div class="fusion-flip-box-wrapper fusion-column col-lg-3 col-md-3 col-sm-3"><div class="fusion-flip-box flip-right" tabindex="0"><div class="flip-box-inner-wrapper" style="min-height: 252px;"><div class="flip-box-front" style="background-color: rgb(246, 246, 246); border-color: rgba(0, 0, 0, 0); border-radius: 4px; border-style: solid; border-width: 1px; color: rgb(116, 116, 116); transition-duration: 0.4s; position: absolute;"><div class="flip-box-front-inner"><div class="flip-box-grafix flip-box-image"><img src="https://rrvblood.wpengine.com/wp-content/uploads/2017/06/AB-.png" width="147" height="147" alt=""></div><h2 class="flip-box-heading without-text fusion-responsive-typography-calculated" style="color: rgb(51, 51, 51); --fontSize:26; line-height: 1.5;" data-fontsize="26" data-lineheight="39px">AB Negative</h2></div></div><div class="flip-box-back" style="background-color: rgb(181, 18, 27); border-color: rgba(0, 0, 0, 0); border-radius: 4px; border-style: solid; border-width: 1px; color: rgb(255, 255, 255); transition-duration: 0.4s; bottom: 0px;"><div class="flip-box-back-inner">
                        <p style="text-align: center;"><strong>1% of the U.S. population has AB- blood</strong></p>
                        <p style="text-align: center; font-size: 13px; line-height: 18px;">• Rarest of blood types<br>
                            • Can donate only to AB patients<br>
                            • Universal Plasma donor<br>
                            • Plasma and platelet pheresis is the best way to help</p>
                    </div></div></div></div></div></div><div class="clearfix"></div><div class="fusion-sep-clear"></div><div class="fusion-separator fusion-full-width-sep" style="margin-left: auto;margin-right: auto;margin-top:20px;margin-bottom:20px;width:100%;"></div><div class="fusion-sep-clear"></div><style type="text/css">.fusion-accordian #accordian-1 .panel-title a .fa-fusion-box:before{ font-size: 13px;}.fusion-accordian #accordian-1 .panel-title a .fa-fusion-box{ color: #ffffff;}.fusion-accordian #accordian-1 .panel-title a{font-size:13px;}.fusion-accordian #accordian-1 .fa-fusion-box { background-color: #333333;border-color: #333333;}.fusion-accordian #accordian-1 .panel-title a:hover,.fusion-accordian #accordian-1 .panel-title a.hover { color: #b5121b;}.fusion-faq-shortcode .fusion-accordian #accordian-1 .fusion-toggle-boxed-mode:hover .panel-title a { color: #b5121b;}.fusion-accordian #accordian-1 .panel-title .active .fa-fusion-box,.fusion-accordian #accordian-1 .panel-title a:hover .fa-fusion-box,.fusion-accordian #accordian-1 .panel-title a.hover .fa-fusion-box { background-color: #b5121b!important;border-color: #b5121b!important;}</style><div class="fusion-faq-shortcode"><div class="fusion-faqs-wrapper" style="display: block;"><div class="accordian fusion-accordian"><div class="panel-group " id="accordian-1"><div class="fusion-panel panel-default fusion-faq-post fusion-faq-post-3733 blood-facts "><span class="entry-title rich-snippet-hidden">Blood Chart</span><span class="vcard rich-snippet-hidden"><span class="fn"><a href="https://www.rrvbc.org/author/bgarrett/" title="Posts by Bryan Garrett" rel="author">Bryan Garrett</a></span></span><span class="updated rich-snippet-hidden">2020-05-06T17:47:31-05:00</span><div class="panel-heading"><h4 class="panel-title toggle fusion-responsive-typography-calculated" data-fontsize="16" data-lineheight="22.08px" style="--fontSize:16; line-height: 1.38; --minFontSize:16;"><a data-toggle="collapse" class="active" data-parent="#accordian-1" data-target="#collapse-1-3733" href="#collapse-1-3733" aria-expanded="true" aria-selected="true"><div class="fusion-toggle-icon-wrapper"><div class="fusion-toggle-icon-wrapper-main"><div class="fusion-toggle-icon-wrapper-sub"><i class="fa-fusion-box" aria-hidden="true"></i></div></div></div><div class="fusion-toggle-heading">Blood Chart</div></a></h4></div><div id="collapse-1-3733" class="panel-collapse collapse in" style="height: auto;"><div class="panel-body toggle-content post-content"><p>This chart shows the various blood types and their frequency in the U.S. population.</p>
                        <p><img class="alignnone size-full wp-image-3323" src="https://rrvblood.wpengine.com/wp-content/uploads/2014/11/blood_type_graph2017.jpg" alt="Blood Type Graph 2017" width="600" height="400" srcset="https://www.rrvbc.org/wp-content/uploads/2014/11/blood_type_graph2017-300x200.jpg 300w, https://www.rrvbc.org/wp-content/uploads/2014/11/blood_type_graph2017.jpg 600w" sizes="(max-width: 600px) 100vw, 600px"></p>
                    </div></div></div><div class="fusion-panel panel-default fusion-faq-post fusion-faq-post-3734 blood-facts "><span class="entry-title rich-snippet-hidden">What is blood?</span><span class="vcard rich-snippet-hidden"><span class="fn"><a href="https://www.rrvbc.org/author/bgarrett/" title="Posts by Bryan Garrett" rel="author">Bryan Garrett</a></span></span><span class="updated rich-snippet-hidden">2020-05-06T17:48:00-05:00</span><div class="panel-heading"><h4 class="panel-title toggle fusion-responsive-typography-calculated" data-fontsize="16" data-lineheight="22.08px" style="--fontSize:16; line-height: 1.38; --minFontSize:16;"><a data-toggle="collapse" class="collapsed" data-parent="#accordian-1" data-target="#collapse-1-3734" href="#collapse-1-3734" aria-expanded="false" aria-selected="false"><div class="fusion-toggle-icon-wrapper"><div class="fusion-toggle-icon-wrapper-main"><div class="fusion-toggle-icon-wrapper-sub"><i class="fa-fusion-box" aria-hidden="true"></i></div></div></div><div class="fusion-toggle-heading">What is blood?</div></a></h4></div><div id="collapse-1-3734" class="panel-collapse collapse" style="height: 0px;"><div class="panel-body toggle-content post-content"><p>Blood is a living tissue composed of blood cells suspended in plasma.</p>
                        <p>The cellular elements, red blood cells, white blood cells and platelets – make up about 45% of the volume of whole blood. Plasma, which is 92% water, makes up the remaining 55%.</p>
                    </div></div></div><div class="fusion-panel panel-default fusion-faq-post fusion-faq-post-3738 blood-facts "><span class="entry-title rich-snippet-hidden">What does blood do?</span><span class="vcard rich-snippet-hidden"><span class="fn"><a href="https://www.rrvbc.org/author/bgarrett/" title="Posts by Bryan Garrett" rel="author">Bryan Garrett</a></span></span><span class="updated rich-snippet-hidden">2020-05-06T17:48:14-05:00</span><div class="panel-heading"><h4 class="panel-title toggle fusion-responsive-typography-calculated" data-fontsize="16" data-lineheight="22.08px" style="--fontSize:16; line-height: 1.38; --minFontSize:16;"><a data-toggle="collapse" class="collapsed" data-parent="#accordian-1" data-target="#collapse-1-3738" href="#collapse-1-3738"><div class="fusion-toggle-icon-wrapper"><div class="fusion-toggle-icon-wrapper-main"><div class="fusion-toggle-icon-wrapper-sub"><i class="fa-fusion-box" aria-hidden="true"></i></div></div></div><div class="fusion-toggle-heading">What does blood do?</div></a></h4></div><div id="collapse-1-3738" class="panel-collapse collapse"><div class="panel-body toggle-content post-content"><p>The average adult has 8 – 12 pints of blood traveling all over his or her body through the heart, lungs, arteries, veins and capillaries. Blood is an essential part of our bodies that transports oxygen, nutrients, and metabolic waste. In addition to all that, blood performs these functions:</p>
                        <ul>
                            <li>Replenishes oxygen and removes carbon dioxide</li>
                            <li>Distributes essential nutrients to cells</li>
                            <li>Carries away metabolic waste materials for disposal</li>
                            <li>Recognizes antigens (foreign substances) and produces antibodies (immune defense mechanisms)</li>
                            <li>Clots cuts, wounds and scratches to prevent bleeding</li>
                        </ul>
                    </div></div></div><div class="fusion-panel panel-default fusion-faq-post fusion-faq-post-3736 blood-facts "><span class="entry-title rich-snippet-hidden">How is blood used?</span><span class="vcard rich-snippet-hidden"><span class="fn"><a href="https://www.rrvbc.org/author/bgarrett/" title="Posts by Bryan Garrett" rel="author">Bryan Garrett</a></span></span><span class="updated rich-snippet-hidden">2020-05-06T17:48:25-05:00</span><div class="panel-heading"><h4 class="panel-title toggle fusion-responsive-typography-calculated" data-fontsize="16" data-lineheight="22.08px" style="--fontSize:16; line-height: 1.38; --minFontSize:16;"><a data-toggle="collapse" class="collapsed" data-parent="#accordian-1" data-target="#collapse-1-3736" href="#collapse-1-3736"><div class="fusion-toggle-icon-wrapper"><div class="fusion-toggle-icon-wrapper-main"><div class="fusion-toggle-icon-wrapper-sub"><i class="fa-fusion-box" aria-hidden="true"></i></div></div></div><div class="fusion-toggle-heading">How is blood used?</div></a></h4></div><div id="collapse-1-3736" class="panel-collapse collapse"><div class="panel-body toggle-content post-content"><p>Blood and its components have many uses.</p>
                        <p>Hospitals stock some of the more common blood components used in emergencies, but usually blood products are not ordered until they are needed. They are kept at the Rock River Valley Blood Center until a hospital orders them.</p>
                        <p>Red cells can be used for 42 days after they are donated. They are used in the treatment of accident victims, to replace blood lost during surgery, to treat burn victims and to increase the blood’s oxygen-carrying capacity. They are also used in the treatment of anemia that can’t be medically corrected.</p>
                        <p>Platelets are stored separate from other components and must be used in the five days following the donation. They are commonly used to treat bone marrow failure, leukemia and cancer patients, low platelet count or other conditions causing abnormally functioning platelets.</p>
                        <p>Plasma has a much longer shelf life and is often frozen for later use. Once thawed, plasma is used during cardiac surgery, for burn victims, and to treat bleeding disorders. For example, bleeding disorders can occur in liver failure, when too much of a blood thinner has been given or when severe bleeding and massive transfusions result in low levels of clotting factors.</p>
                        <p>Plasma is often used to make therapies for bleeding disorders:</p>
                        <p>Factor VII concentrate is used in the treatment and prevention of bleeding episodes.</p>
                        <p>Factor VIII concentrate and cryoprecipitate are used by patients with hemophilia A (classic hemophilia), which is caused by a deficiency of factor VIII. Cryoprecipitate is prepared from plasma and contains fibrinogen, von Willebrand factor, factor VIII, factor XIII and fibronectin.</p>
                        <p>Factor IX concentrate is used by patients with hemophilia B (“Christmas disease”), which is caused by a deficiency of clotting factor IX.</p>
                        <p><strong>Transfusions</strong></p>
                        <p>A transfusion is a procedure that replaces the blood lost by a patient with the blood of a generous donor like you!</p>
                        <p><img src="https://www.rrvbc.org/wp-content/uploads/2017/08/HOWISBLOODUSED2.png" alt="" width="836" height="1546" class="alignnone size-full wp-image-3843" srcset="https://www.rrvbc.org/wp-content/uploads/2017/08/HOWISBLOODUSED2-162x300.png 162w, https://www.rrvbc.org/wp-content/uploads/2017/08/HOWISBLOODUSED2-200x370.png 200w, https://www.rrvbc.org/wp-content/uploads/2017/08/HOWISBLOODUSED2-400x740.png 400w, https://www.rrvbc.org/wp-content/uploads/2017/08/HOWISBLOODUSED2-554x1024.png 554w, https://www.rrvbc.org/wp-content/uploads/2017/08/HOWISBLOODUSED2-600x1110.png 600w, https://www.rrvbc.org/wp-content/uploads/2017/08/HOWISBLOODUSED2-768x1420.png 768w, https://www.rrvbc.org/wp-content/uploads/2017/08/HOWISBLOODUSED2-800x1479.png 800w, https://www.rrvbc.org/wp-content/uploads/2017/08/HOWISBLOODUSED2.png 836w" sizes="(max-width: 836px) 100vw, 836px"></p>
                        <p>After you give your blood, while you’re snacking on cookies and showing off your arm wrap, your blood begins its journey to save lives! Through one donation, you can help save as many as up to 3 lives. No wonder RRVBC donors and volunteers feel so amazing. And, who ever thought saving lives could be this easy?</p>
                    </div></div></div><div class="fusion-panel panel-default fusion-faq-post fusion-faq-post-3735 blood-facts "><span class="entry-title rich-snippet-hidden">30 Fascinating Blood Facts</span><span class="vcard rich-snippet-hidden"><span class="fn"><a href="https://www.rrvbc.org/author/bgarrett/" title="Posts by Bryan Garrett" rel="author">Bryan Garrett</a></span></span><span class="updated rich-snippet-hidden">2020-05-06T17:48:58-05:00</span><div class="panel-heading"><h4 class="panel-title toggle fusion-responsive-typography-calculated" data-fontsize="16" data-lineheight="22.08px" style="--fontSize:16; line-height: 1.38; --minFontSize:16;"><a data-toggle="collapse" class="collapsed" data-parent="#accordian-1" data-target="#collapse-1-3735" href="#collapse-1-3735"><div class="fusion-toggle-icon-wrapper"><div class="fusion-toggle-icon-wrapper-main"><div class="fusion-toggle-icon-wrapper-sub"><i class="fa-fusion-box" aria-hidden="true"></i></div></div></div><div class="fusion-toggle-heading">30 Fascinating Blood Facts</div></a></h4></div><div id="collapse-1-3735" class="panel-collapse collapse"><div class="panel-body toggle-content post-content"><p><img class="alignnone size-full wp-image-3447" src="https://rrvblood.wpengine.com/wp-content/uploads/2017/07/30facts.png" alt="" width="399" height="185" srcset="https://www.rrvbc.org/wp-content/uploads/2017/07/30facts-300x139.png 300w, https://www.rrvbc.org/wp-content/uploads/2017/07/30facts.png 399w" sizes="(max-width: 399px) 100vw, 399px"></p>
                        <p><strong>01.</strong> Anyone in good health, at least 17 years old (or 16 years old with parental consent – <a href="https://www.rrvbc.org/wp-content/uploads/2020/04/Sixteen-Year-Old-Consent.pdf">click here for consent form</a>), and at least 110 pounds may donate whole blood every 56 days.<br>
                            <strong>02.</strong> 4.5 million American lives are saved each year by blood transfusions.<br>
                            <strong>03.</strong> 40,000 pints of donated blood are used each day in the United States.<br>
                            <strong>04.</strong> Someone needs blood every two seconds.</p>
                        <p><img class="alignnone size-full wp-image-3449" src="https://rrvblood.wpengine.com/wp-content/uploads/2017/07/fact05.png" alt="" width="399" height="185" srcset="https://www.rrvbc.org/wp-content/uploads/2017/07/fact05-300x139.png 300w, https://www.rrvbc.org/wp-content/uploads/2017/07/fact05.png 399w" sizes="(max-width: 399px) 100vw, 399px"></p>
                        <p><strong>06.</strong> Up to 3 lives are saved by one pint of donated blood.<br>
                            <strong>07.</strong> Between 8-12 pints of blood are in the body of an average adult.<br>
                            <strong>08.</strong> One unit of blood is ~525 mL, which is roughly the equivalent of one pint.<br>
                            <strong>09.</strong> A newborn baby has about one cup of blood in his body.<br>
                            <strong>10.</strong> The average transfusion patient receives 3 units of red blood cells.<br>
                            <strong>11.</strong> A, B, AB and O are the four main types of blood types. AB is the universal recipient, O negative is the universal donor.<br>
                            <strong>12.</strong> Blood centers often run short of types O and B blood.</p>
                        <p><img class="alignnone size-full wp-image-3451" src="https://rrvblood.wpengine.com/wp-content/uploads/2017/07/fact13.png" alt="" width="399" height="185" srcset="https://www.rrvbc.org/wp-content/uploads/2017/07/fact13-300x139.png 300w, https://www.rrvbc.org/wp-content/uploads/2017/07/fact13.png 399w" sizes="(max-width: 399px) 100vw, 399px"></p>
                        <p><strong>14.</strong> The actual blood donation usually takes less than ten minutes. The entire process from the time you sign in to the time you leave takes about an hour.<br>
                            <strong>15.</strong> Giving blood will not decrease your strength.</p>
                        <p><img class="alignnone size-full wp-image-3453" src="https://rrvblood.wpengine.com/wp-content/uploads/2017/07/fact16.png" alt="" width="399" height="185" srcset="https://www.rrvbc.org/wp-content/uploads/2017/07/fact16-300x139.png 300w, https://www.rrvbc.org/wp-content/uploads/2017/07/fact16.png 399w" sizes="(max-width: 399px) 100vw, 399px"></p>
                        <p><strong>17.</strong> Red blood cells carry oxygen to the body’s organs and tissue.<br>
                            <strong>18.</strong> There are one billion red blood cells in two to three drops of blood.<br>
                            <strong>19.</strong> Platelets support blood clotting and give those with leukemia and other cancers a chance to live.<br>
                            <strong>20.</strong> The shelf life of donated red blood cells is 42 days.<br>
                            <strong>21.</strong> The shelf life of donated platelets is five days.<br>
                            <strong>22.</strong> Car accident and blood loss victims may need transfusions of 50 pints or more of red blood cells.</p>
                        <p><img class="alignnone size-full wp-image-3455" src="https://rrvblood.wpengine.com/wp-content/uploads/2017/07/fact23.png" alt="" width="399" height="185" srcset="https://www.rrvbc.org/wp-content/uploads/2017/07/fact23-300x139.png 300w, https://www.rrvbc.org/wp-content/uploads/2017/07/fact23.png 399w" sizes="(max-width: 399px) 100vw, 399px"></p>
                        <p><strong>24.</strong> Severe burn victims may need 20 units of platelets during their treatment.<br>
                            <strong>25.</strong> Children being treated for cancer, premature infants and children having heart surgery need blood and platelets from donors of all types.<br>
                            <strong>26.</strong> Cancer, transplant and trauma patients, and patients undergoing open-heart surgery often require platelet transfusions to survive.<br>
                            <strong>27.</strong> 500,000 Americans donated blood in the days following the September 11th attacks.</p>
                        <p><strong>28.</strong> 94% of blood donors are registered voters.<br>
                            <strong>29.</strong> Bone marrow transplant patients can use up to 120 platelets and red blood cells from about 20 people.<br>
                            <strong>30.</strong> 17% of non-donors cite “never thought about it” as the main reason for not giving, while 15% say they’re too busy. The #1 reason donors say they give is because they “want to help others.”</p>
                    </div></div></div></div></div></div></div><div class="fusion-clearfix"></div></div></div></div></div>
                </div>
            </div>
        </section>

    </div>  <!-- fusion-row -->
</body>
</html>


